name: automated ecommerce website validation
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: deps-pythonselenium-${{ hashFiles('**/requirements.txt')}}
                restore-keys: |
                  deps-pythonselenium-
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Install latest Chrome & ChromeDriver
              run: |
               sudo apt update
               sudo apt install -y google-chrome-stable chromium-driver jq
               CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
               CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.version")
               echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
               wget -N "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
               unzip chromedriver-linux64.zip
               sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
               sudo chmod +x /usr/local/bin/chromedriver
               chromedriver --version

            - name: Run Selenium Tests
              run: pytest --html=reports/test_report.html --self-contained-html
            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: reports/test_report.html
    