name: automated ecommerce website validation
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Install webdriver for selenium
              run: |
                wget https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
                unzip chromedriver_linux64.zip
                sudo mv chromedriver /usr/local/bin/
                chmod +x /usr/local/bin/chromedriver
            - name: Run Selenium Tests
              run: pytest --html=reports/test_report.html --self-contained-html
            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: reports/test_report.html
    

