name: automated ecommerce website validation
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.13"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Install latest Chrome & ChromeDriver
              run: |
               sudo apt update
               sudo apt install -y google-chrome-stable
               CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
               CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
               wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
               unzip chromedriver_linux64.zip
               sudo mv chromedriver /usr/local/bin/
               chmod +x /usr/local/bin/chromedriver
               chromedriver --version
            - name: Run Selenium Tests
              run: pytest --html=reports/test_report.html --self-contained-html
            - name: Upload Test Reports
              uses: actions/upload-artifact@v4
              with:
                name: test-report
                path: reports/test_report.html
    